improve containers + add cron execution example

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -53,8 +53,7 @@ jobs:
       - name: Execute deployment commands via SSH
         uses: appleboy/ssh-action@v1.0.3
         env:
-          COMPOSE_OVERRIDE: |
-            ${{ secrets.COMPOSE_OVERRIDE || '' }}
+          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
         with:
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USERNAME }}
@@ -63,18 +62,30 @@ jobs:
           script: |
             set -x
             
-            # Rsync files from /tmp dir
-            rsync -av --exclude='.vscode' --exclude='.idea' --exclude='.git' --exclude='.github' ${{ env.TMP_DIRECTORY }} ${{ secrets.SSH_DIRECTORY }} 
+            # Create workspace if missing
+            mkdir -p ${{ secrets.SSH_DIRECTORY }} 
             
             # Go to workspace
             cd ${{ secrets.SSH_DIRECTORY }}
+            
+            # Cleanup old src files
+            rm -rf src || true
+            
+            # Rsync files from /tmp dir
+            rsync -av --exclude='.vscode' --exclude='.idea' --exclude='.git' --exclude='.github' ${{ env.TMP_DIRECTORY }} ${{ secrets.SSH_DIRECTORY }}
             
             # Write compose.prod.override.yaml
             cat <<'EOF' > compose.prod.override.yaml
             ${{ secrets.COMPOSE_OVERRIDE }}
             EOF
             
+            # Reset DB if commit message flag is present
+            if [[ "$COMMIT_MESSAGE" == *"(reset-db)"* ]]; then
+               docker compose -f compose.yaml -f compose.prod.yaml -f compose.prod.override.yaml down -v
+            fi
+            
             # Restart containers
+            docker compose -f compose.yaml -f compose.prod.yaml -f compose.prod.override.yaml build app
             docker compose -f compose.yaml -f compose.prod.yaml -f compose.prod.override.yaml up -d --remove-orphans --build --force-recreate --wait
             
             # Prune dangling images
